package com.sdtechtop.ui.colorpicker;

public class COLORS
{
	public static String[] redColors,greenColors,
	blueColors,yellowColors,pinkColors,
	brownColors,greyColors,tealColors,orangeColors,
	purpleColors,indigoColors,deepOrangeColors,
	deepPurpleColors,blueGreyColors,lightGreenColors,
	limeColors,amberColors,cyanColors,lightBlueColors;
	static {
		amberColors = new String[]{
			getString(R.string.amber_50),
			getString(R.string.amber_100),
			getString(R.string.amber_200),
			getString(R.string.amber_300),
			getString(R.string.amber_400),
			getString(R.string.amber_500),
			getString(R.string.amber_600),
			getString(R.string.amber_700),
			getString(R.string.amber_800),
			getString(R.string.amber_900),
			getString(R.string.amber_A100),
			getString(R.string.amber_A200),
			getString(R.string.amber_A400),
			getString(R.string.amber_A700)
		};
		greyColors = new String[]{
		getString(R.string.grey_50),
		getString(R.string.grey_100),
		getString(R.string.grey_200),
		getString(R.string.grey_300),
		getString(R.string.grey_400),
		getString(R.string.grey_500),
		getString(R.string.grey_600),
		getString(R.string.grey_700),
		getString(R.string.grey_800),
		getString(R.string.grey_900)
		};
		blueGreyColors = new String[]{
		getString(R.string.blue_grey_50),
		getString(R.string.blue_grey_100),
		getString(R.string.blue_grey_200),
		getString(R.string.blue_grey_300),
		getString(R.string.blue_grey_400),
		getString(R.string.blue_grey_500),
		getString(R.string.blue_grey_600),
		getString(R.string.blue_grey_700),
		getString(R.string.blue_grey_800),
		getString(R.string.blue_grey_900)
		};
		brownColors = new String[]{
		getString(R.string.brown_50),
		getString(R.string.brown_100),
		getString(R.string.brown_200),
		getString(R.string.brown_300),
		getString(R.string.brown_400),
		getString(R.string.brown_500),
		getString(R.string.brown_600),
		getString(R.string.brown_700),
		getString(R.string.brown_800),
		getString(R.string.brown_900)
		};
		blueColors = new String[]{
		getString(R.string.blue_50),
		getString(R.string.blue_100),
		getString(R.string.blue_200),
		getString(R.string.blue_300),
		getString(R.string.blue_400),
		getString(R.string.blue_500),
		getString(R.string.blue_600),
		getString(R.string.blue_700),
		getString(R.string.blue_800),
		getString(R.string.blue_900),
		getString(R.string.blue_A100),
		getString(R.string.blue_A200),
		getString(R.string.blue_A400),
		getString(R.string.blue_A700)
		};
		greenColors = new String[]{
		getString(R.string.green_50),
		getString(R.string.green_100),
		getString(R.string.green_200),
		getString(R.string.green_300),
		getString(R.string.green_400),
		getString(R.string.green_500),
		getString(R.string.green_600),
		getString(R.string.green_700),
		getString(R.string.green_800),
		getString(R.string.green_900),
		getString(R.string.green_A100),
		getString(R.string.green_A200),
		getString(R.string.green_A400),
		getString(R.string.green_A700)
		};
		pinkColors = new String[]{
		getString(R.string.pink_50),
		getString(R.string.pink_100),
		getString(R.string.pink_200),
		getString(R.string.pink_300),
		getString(R.string.pink_400),
		getString(R.string.pink_500),
		getString(R.string.pink_600),
		getString(R.string.pink_700),
		getString(R.string.pink_800),
		getString(R.string.pink_900),
		getString(R.string.pink_A100),
		getString(R.string.pink_A200),
		getString(R.string.pink_A400),
		getString(R.string.pink_A700)
		};
		purpleColors = new String[]{
		getString(R.string.purple_50),
		getString(R.string.purple_100),
		getString(R.string.purple_200),
		getString(R.string.purple_300),
		getString(R.string.purple_400),
		getString(R.string.purple_500),
		getString(R.string.purple_600),
		getString(R.string.purple_700),
		getString(R.string.purple_800),
		getString(R.string.purple_900),
		getString(R.string.purple_A100),
		getString(R.string.purple_A200),
		getString(R.string.purple_A400),
		getString(R.string.purple_A700)
		};
		indigoColors = new String[]{
		getString(R.string.indigo_50),
		getString(R.string.indigo_100),
		getString(R.string.indigo_200),
		getString(R.string.indigo_300),
		getString(R.string.indigo_400),
		getString(R.string.indigo_500),
		getString(R.string.indigo_600),
		getString(R.string.indigo_700),
		getString(R.string.indigo_800),
		getString(R.string.indigo_900),
		getString(R.string.indigo_A100),
		getString(R.string.indigo_A200),
		getString(R.string.indigo_A400),
		getString(R.string.indigo_A700)
		};
		tealColors = new String[]{
		getString(R.string.teal_50),
		getString(R.string.teal_100),
		getString(R.string.teal_200),
		getString(R.string.teal_300),
		getString(R.string.teal_400),
		getString(R.string.teal_500),
		getString(R.string.teal_600),
		getString(R.string.teal_700),
		getString(R.string.teal_800),
		getString(R.string.teal_900),
		getString(R.string.teal_A100),
		getString(R.string.teal_A200),
		getString(R.string.teal_A400),
		getString(R.string.teal_A700)
		};
		limeColors = new String[]{
		getString(R.string.lime_50),
		getString(R.string.lime_100),
		getString(R.string.lime_200),
		getString(R.string.lime_300),
		getString(R.string.lime_400),
		getString(R.string.lime_500),
		getString(R.string.lime_600),
		getString(R.string.lime_700),
		getString(R.string.lime_800),
		getString(R.string.lime_900),
		getString(R.string.lime_A100),
		getString(R.string.lime_A200),
		getString(R.string.lime_A400),
		getString(R.string.lime_A700)
		};
		orangeColors = new String[]{
		getString(R.string.orange_50),
		getString(R.string.orange_100),
		getString(R.string.orange_200),
		getString(R.string.orange_300),
		getString(R.string.orange_400),
		getString(R.string.orange_500),
		getString(R.string.orange_600),
		getString(R.string.orange_700),
		getString(R.string.orange_800),
		getString(R.string.orange_900),
		getString(R.string.orange_A100),
		getString(R.string.orange_A200),
		getString(R.string.orange_A400),
		getString(R.string.orange_A700)
		};
		cyanColors = new String[]{
		getString(R.string.cyan_50),
		getString(R.string.cyan_100),
		getString(R.string.cyan_200),
		getString(R.string.cyan_300),
		getString(R.string.cyan_400),
		getString(R.string.cyan_500),
		getString(R.string.cyan_600),
		getString(R.string.cyan_700),
		getString(R.string.cyan_800),
		getString(R.string.cyan_900),
		getString(R.string.cyan_A100),
		getString(R.string.cyan_A200),
		getString(R.string.cyan_A400),
		getString(R.string.cyan_A700)
		};
		redColors = new String[]{
		getString(R.string.red_50),
		getString(R.string.red_100),
		getString(R.string.red_200),
		getString(R.string.red_300),
		getString(R.string.red_400),
		getString(R.string.red_500),
		getString(R.string.red_600),
		getString(R.string.red_700),
		getString(R.string.red_800),
		getString(R.string.red_900),
		getString(R.string.red_A100),
		getString(R.string.red_A200),
		getString(R.string.red_A400),
		getString(R.string.red_A700)
		};
		yellowColors = new String[]{
		getString(R.string.yellow_50),
		getString(R.string.yellow_100),
		getString(R.string.yellow_200),
		getString(R.string.yellow_300),
		getString(R.string.yellow_400),
		getString(R.string.yellow_500),
		getString(R.string.yellow_600),
		getString(R.string.yellow_700),
		getString(R.string.yellow_800),
		getString(R.string.yellow_900),
		getString(R.string.yellow_A100),
		getString(R.string.yellow_A200),
		getString(R.string.yellow_A400),
		getString(R.string.yellow_A700)
		};
		lightGreenColors = new String[]{
		getString(R.string.light_green_50),
		getString(R.string.light_green_100),
		getString(R.string.light_green_200),
		getString(R.string.light_green_300),
		getString(R.string.light_green_400),
		getString(R.string.light_green_500),
		getString(R.string.light_green_600),
		getString(R.string.light_green_700),
		getString(R.string.light_green_800),
		getString(R.string.light_green_900),
		getString(R.string.light_green_A100),
		getString(R.string.light_green_A200),
		getString(R.string.light_green_A400),
		getString(R.string.light_green_A700)
		};
		lightBlueColors = new String[]{
		getString(R.string.light_blue_50),
		getString(R.string.light_blue_100),
		getString(R.string.light_blue_200),
		getString(R.string.light_blue_300),
		getString(R.string.light_blue_400),
		getString(R.string.light_blue_500),
		getString(R.string.light_blue_600),
		getString(R.string.light_blue_700),
		getString(R.string.light_blue_800),
		getString(R.string.light_blue_900),
		getString(R.string.light_blue_A100),
		getString(R.string.light_blue_A200),
		getString(R.string.light_blue_A400),
		getString(R.string.light_blue_A700)
		};
		deepOrangeColors = new String[]{
		getString(R.string.deep_orange_50),
		getString(R.string.deep_orange_100),
		getString(R.string.deep_orange_200),
		getString(R.string.deep_orange_300),
		getString(R.string.deep_orange_400),
		getString(R.string.deep_orange_500),
		getString(R.string.deep_orange_600),
		getString(R.string.deep_orange_700),
		getString(R.string.deep_orange_800),
		getString(R.string.deep_orange_900),
		getString(R.string.deep_orange_A100),
		getString(R.string.deep_orange_A200),
		getString(R.string.deep_orange_A400),
		getString(R.string.deep_orange_A700)
		};
		deepPurpleColors = new String[]{
		getString(R.string.deep_purple_50),
		getString(R.string.deep_purple_100),
		getString(R.string.deep_purple_200),
		getString(R.string.deep_purple_300),
		getString(R.string.deep_purple_400),
		getString(R.string.deep_purple_500),
		getString(R.string.deep_purple_600),
		getString(R.string.deep_purple_700),
		getString(R.string.deep_purple_800),
		getString(R.string.deep_purple_900),
		getString(R.string.deep_purple_A100),
		getString(R.string.deep_purple_A200),
		getString(R.string.deep_purple_A400),
		getString(R.string.deep_purple_A700)
		};
	}

	private static String getString(int strId) {
		return Utils.getActivity().getResources().getString(strId);
	}
	
}
